apiVersion: v1
kind: ConfigMap
metadata:
  name: app-secret
data:
  default.conf: |
    server {
        listen       80 default_server;
        server_name  _;

        default_type text/plain;

        location / {
            return 200 'OK $hostname request: $request_uri\n';
        }
        
        location /secret {
            root /opt;
        }
    }
