version: "2.4"

services:
 web:
  build: .
  ports:
   - "8080:5000"
  depends_on:
   redis:
    condition: service_healthy

 redis:
  image: redis:alpine
  volumes:
   - type: volume
     source: redis-data
     target: /data
  healthcheck:
   test: ["CMD", "redis-cli", "ping"]
   interval: 3s
   timeout: 5s
   retries: 5

volumes:
  redis-data: